import fs from'node:fs/promises';import zlib from'node:zlib';
const OPS=['SIGESIG','HXW','GLY'],C='data/electroverse/tariff_cache',M='data/electroverse/irve_location_mapping.json',O='data/platforms/electroverse/france-evse';
const n=x=>String(x??'').trim().toUpperCase().replace(/[^A-Z0-9]/g,''),t=x=>String(x??'').trim(),op=p=>{const m=String(p).match(/^FR([A-Z0-9]{1,8})E/);return m?m[1]:'UNKNOWN'};
const map=JSON.parse(await fs.readFile(M,'utf8')),byPk=new Map((map.mappings||[]).map(x=>[String(x.electroverseLocationPk),x])),owners=new Map();
for(const x of map.mappings||[])for(const p of x.irvePdcIds||[]){const k=n(p),s=owners.get(k)||new Set();s.add(String(x.irveStationId||''));owners.set(k,s)}
const om=JSON.parse(await fs.readFile(O+'/manifest.json','utf8')),pub=new Set(),spks=new Set();
for(const q of om.tiles||[]){const z=JSON.parse(zlib.gunzipSync(await fs.readFile(O+'/'+q.file)));for(const a of z.emspOffers||[]){for(const p of a.evseIds||[])pub.add(n(p));for(const p of a?.metadata?.electroverseEvsePks||[])if(p!=null)spks.add(String(p));if(a?.metadata?.electroverseEvsePk!=null)spks.add(String(a.metadata.electroverseEvsePk));}}
const cm=JSON.parse(await fs.readFile(C+'/manifest.json','utf8')),R={};for(const x of OPS)R[x]={operator:x,missing:0,locations:0,sources:0,shape:{},cardinality:{},parentFirstTargets:0,suffixTargets:0,samples:[]};
for(const sh of cm.shards||[]){const d=JSON.parse(await fs.readFile(C+'/'+sh.file,'utf8'));for(const row of Object.values(d.stations||{})){const m=byPk.get(String(row.electroverseLocationPk));if(!m)continue;const local=[...new Set((m.irvePdcIds||row.irvePdcIds||[]).map(n).filter(Boolean))],miss=local.filter(p=>!pub.has(p));const src=(row.tariff?.evses||[]).filter(e=>e?.pk!=null&&!spks.has(String(e.pk)));
for(const code of OPS){const mt=miss.filter(p=>op(p)===code);if(!mt.length)continue;const r=R[code];r.missing+=mt.length;r.locations++;r.sources+=src.length;r.cardinality[src.length+'->'+mt.length]=(r.cardinality[src.length+'->'+mt.length]||0)+1;let pf=0,sf=0;
for(const e of src){const raw=t(e.physicalReference),k=n(raw);const shape=/^MAT[-_]?/i.test(raw)?'MAT':/^FR\*/i.test(raw)?'OCPI':/^\d+$/.test(raw)?'NUMERIC':/^[A-Z]+\d+/i.test(raw)?'ALNUM':'OTHER';r.shape[shape]=(r.shape[shape]||0)+1;const hits=mt.filter(p=>k.length>=4&&p.endsWith(k)&&(owners.get(p)?.size||0)===1);if(hits.length===1)sf++;const mm=raw.match(/^FR\*([A-Z0-9]+)\*E(.+?)\*(\d+)\*(\d+)$/i);if(mm){const target=n('FR'+mm[1]+'E'+mm[2])+String(Number(mm[3]));if(mt.includes(target)&&(owners.get(target)?.size||0)===1)pf++;}}
r.parentFirstTargets+=pf;r.suffixTargets+=sf;if(r.samples.length<15)r.samples.push({locationPk:String(row.electroverseLocationPk),station:m.irveStationId,missing:mt.slice(0,20),refs:src.slice(0,25).map(e=>t(e.physicalReference)),parentFirstHits:pf,suffixHits:sf});}}}
await fs.mkdir('reports/electroverse',{recursive:true});for(const code of OPS){await fs.writeFile('reports/electroverse/'+code.toLowerCase()+'-gap-analysis.json',JSON.stringify(R[code],null,2)+'\n');console.log(JSON.stringify(R[code],null,2))}
