#!/usr/bin/env python3
"""Cross-match a tiny exact PUN Go Electric sample against public NextCharge reads.

Safety scope:
- consumes the published V9 PUN sample generated by go_electric_pun_v9_sample.py;
- queries only the two already validated public web-map read endpoints:
  /apps/map/apis/stationsGrid and /apps/map/apis/station;
- targets at most one operational station in each of four power classes;
- uses a small bounding box around each known PUN coordinate;
- never calls charge, payment, reservation, account, session, or mutation APIs.
"""
from __future__ import annotations

import json
import math
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

GRID_ENDPOINT = "https://nextcharge.app/apps/map/apis/stationsGrid"
STATION_ENDPOINT = "https://nextcharge.app/apps/map/apis/station"
REFERER = "https://nextcharge.app/map?nextcharge=only"
USER_AGENT = "TeslaChargeCompanion-DataLab/1.0 (+read-only exact-match research)"
APP_VERSION = "6.1.4"
OWNER = "ITGES"
MAX_TARGETS = 4
BBOX_DEGREES = 0.012
MAX_MATCH_DISTANCE_M = 1200.0
MAX_RESPONSE_BYTES = 6_000_000
TARGET_CLASSES = ["AC_22_or_less", "DC_23_60", "DC_61_150", "HPC_over_150"]
RELEVANT_TERMS = (
    "tariff", "price", "fee", "connector", "evse", "provider", "operator",
    "currency", "power", "stationfee", "idstation", "idconnector", "idevse",
)
SENSITIVE_KEY_PARTS = (
    "token", "secret", "password", "cookie", "authorization", "card", "pan",
    "paymentmethod", "clientsecret", "accesskey", "nonce",
)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def headers() -> dict[str, str]:
    return {
        "User-Agent": USER_AGENT,
        "Accept": "application/json, text/javascript, */*; q=0.01",
        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        "client-type": "webapp",
        "Origin": "https://nextcharge.app",
        "Referer": REFERER,
        "X-Requested-With": "XMLHttpRequest",
    }


def post_form(endpoint: str, form: dict[str, Any]) -> tuple[int, Any, int]:
    if endpoint not in {GRID_ENDPOINT, STATION_ENDPOINT}:
        raise RuntimeError(f"endpoint not allowed: {endpoint}")
    req = urllib.request.Request(
        endpoint,
        data=urllib.parse.urlencode(form).encode("utf-8"),
        method="POST",
        headers=headers(),
    )
    try:
        with urllib.request.urlopen(req, timeout=40) as resp:
            raw = resp.read(MAX_RESPONSE_BYTES + 1)
            if len(raw) > MAX_RESPONSE_BYTES:
                raise RuntimeError("response exceeds safety limit")
            return resp.status, json.loads(raw.decode(resp.headers.get_content_charset() or "utf-8", errors="replace")), len(raw)
    except urllib.error.HTTPError as exc:
        raw = exc.read(MAX_RESPONSE_BYTES + 1)
        try:
            payload: Any = json.loads(raw.decode("utf-8", errors="replace"))
        except Exception:
            payload = {"bodyPrefix": raw.decode("utf-8", errors="replace")[:1000]}
        return exc.code, payload, len(raw)


def safe_key(key: str) -> bool:
    low = key.lower().replace("_", "")
    return not any(x in low for x in SENSITIVE_KEY_PARTS)


def redact(value: Any, depth: int = 0, list_limit: int = 20) -> Any:
    if depth > 10:
        return "<depth-limit>"
    if isinstance(value, dict):
        out: dict[str, Any] = {}
        for k, v in value.items():
            sk = str(k)
            out[sk] = redact(v, depth + 1, list_limit) if safe_key(sk) else "<redacted>"
        return out
    if isinstance(value, list):
        shown = [redact(v, depth + 1, list_limit) for v in value[:list_limit]]
        if len(value) > list_limit:
            shown.append({"_truncatedItems": len(value) - list_limit})
        return shown
    if isinstance(value, str):
        return value[:4000]
    return value


def choose_targets(report: dict[str, Any]) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    groups = report.get("samplesByStationMaxPowerClass") or {}
    for class_name in TARGET_CLASSES:
        rows = groups.get(class_name) or []
        target = next((x for x in rows if str(x.get("status") or "").upper() == "OPERATIONAL"), None)
        if target:
            selected.append({"powerClass": class_name, **target})
    return selected[:MAX_TARGETS]


def num(d: dict[str, Any], names: tuple[str, ...]) -> float | None:
    for name in names:
        if name in d:
            try:
                return float(d[name])
            except (TypeError, ValueError):
                pass
    return None


def station_candidates(payload: Any) -> list[dict[str, Any]]:
    found: list[dict[str, Any]] = []
    seen: set[str] = set()
    def walk(node: Any, depth: int = 0) -> None:
        if depth > 8 or len(found) >= 500:
            return
        if isinstance(node, dict):
            sid = str(node.get("idStation") or node.get("stationId") or node.get("station_id") or "").strip()
            lat = num(node, ("latitude", "lat"))
            lon = num(node, ("longitude", "lng", "lon"))
            if sid and lat is not None and lon is not None and sid not in seen:
                seen.add(sid)
                found.append(node)
            for v in node.values():
                walk(v, depth + 1)
        elif isinstance(node, list):
            for v in node[:2000]:
                walk(v, depth + 1)
    walk(payload)
    return found


def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371000.0
    a1, a2 = math.radians(lat1), math.radians(lat2)
    da = math.radians(lat2 - lat1)
    do = math.radians(lon2 - lon1)
    a = math.sin(da / 2) ** 2 + math.cos(a1) * math.cos(a2) * math.sin(do / 2) ** 2
    return 2 * r * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def find_relevant(value: Any, prefix: str = "", depth: int = 0, out: dict[str, Any] | None = None) -> dict[str, Any]:
    if out is None:
        out = {}
    if depth > 10 or len(out) >= 500:
        return out
    if isinstance(value, dict):
        for k, v in value.items():
            sk = str(k)
            path = f"{prefix}.{sk}" if prefix else sk
            low = sk.lower().replace("_", "")
            if any(term in low for term in RELEVANT_TERMS) and safe_key(sk):
                out[path] = redact(v, list_limit=30)
            find_relevant(v, path, depth + 1, out)
    elif isinstance(value, list):
        for idx, v in enumerate(value[:30]):
            find_relevant(v, f"{prefix}[{idx}]", depth + 1, out)
    return out


def find_key_values(value: Any, wanted: set[str], prefix: str = "", depth: int = 0, out: list[dict[str, Any]] | None = None) -> list[dict[str, Any]]:
    if out is None:
        out = []
    if depth > 10 or len(out) >= 100:
        return out
    if isinstance(value, dict):
        for k, v in value.items():
            path = f"{prefix}.{k}" if prefix else str(k)
            if str(k).lower() in wanted and safe_key(str(k)):
                out.append({"path": path, "value": redact(v, list_limit=40)})
            find_key_values(v, wanted, path, depth + 1, out)
    elif isinstance(value, list):
        for idx, v in enumerate(value[:50]):
            find_key_values(v, wanted, f"{prefix}[{idx}]", depth + 1, out)
    return out


def probe_target(target: dict[str, Any]) -> dict[str, Any]:
    lat, lon = float(target["lat"]), float(target["lon"])
    window = {
        "lonSW": lon - BBOX_DEGREES,
        "lonNE": lon + BBOX_DEGREES,
        "latSW": lat - BBOX_DEGREES,
        "latNE": lat + BBOX_DEGREES,
        "filterIsReady": "true",
        "includeNextcharge": "only",
        "favorites": "0",
        "userCountry": "IT",
        "owner": OWNER,
        "osType": "desktop",
        "appVersion": APP_VERSION,
        "idGroupProvider": "",
    }
    grid_status, grid_payload, grid_bytes = post_form(GRID_ENDPOINT, window)
    candidates = station_candidates(grid_payload) if grid_status == 200 else []
    ranked: list[dict[str, Any]] = []
    for c in candidates:
        clat = num(c, ("latitude", "lat"))
        clon = num(c, ("longitude", "lng", "lon"))
        sid = str(c.get("idStation") or c.get("stationId") or c.get("station_id") or "").strip()
        if clat is None or clon is None or not sid:
            continue
        ranked.append({"idStation": sid, "lat": clat, "lon": clon, "distanceM": round(haversine_m(lat, lon, clat, clon), 1), "gridRecord": redact(c, list_limit=10)})
    ranked.sort(key=lambda x: x["distanceM"])
    nearest = ranked[0] if ranked else None
    result: dict[str, Any] = {
        "pun": redact(target, list_limit=30),
        "grid": {
            "httpStatus": grid_status,
            "responseBytes": grid_bytes,
            "candidateCount": len(candidates),
            "nearestCandidates": ranked[:8],
        },
        "matched": False,
    }
    if not nearest or nearest["distanceM"] > MAX_MATCH_DISTANCE_M:
        result["matchReason"] = "no_nextcharge_station_within_distance_threshold"
        return result

    sid = nearest["idStation"]
    detail_status, detail, detail_bytes = post_form(STATION_ENDPOINT, {"idStation": sid, "osType": "desktop", "appVersion": APP_VERSION})
    result["nextcharge"] = {
        "idStation": sid,
        "distanceM": nearest["distanceM"],
        "detailHttpStatus": detail_status,
        "detailResponseBytes": detail_bytes,
        "relevantFields": find_relevant(detail),
        "tariffEMP": find_key_values(detail, {"tariffemp"}),
        "priceRateStandard": find_key_values(detail, {"priceratestandard"}),
        "idEVSE": find_key_values(detail, {"idevse"}),
        "idConnector": find_key_values(detail, {"idconnector"}),
        "providerFields": find_key_values(detail, {"provider", "providername", "operator", "operatorname", "nameprovider"}),
        "redactedDetail": redact(detail, list_limit=40),
    }
    result["matched"] = detail_status == 200
    result["matchReason"] = "nearest_public_station_detail_read"
    return result


def main() -> None:
    sample_path = Path("artifacts/go_electric_pun_v9_sample.json")
    if not sample_path.exists():
        raise SystemExit("missing PUN sample artifact")
    pun = json.loads(sample_path.read_text(encoding="utf-8"))
    targets = choose_targets(pun)
    if len(targets) < 3:
        raise SystemExit(f"not enough operational representative targets: {len(targets)}")
    results = [probe_target(t) for t in targets]
    report = {
        "schemaVersion": 1,
        "generatedAt": now_iso(),
        "policy": {
            "readOnly": True,
            "authenticated": False,
            "remoteMutation": False,
            "allowedEndpoints": [GRID_ENDPOINT, STATION_ENDPOINT],
            "chargingActionsAllowed": False,
            "paymentActionsAllowed": False,
            "reservationActionsAllowed": False,
            "accountActionsAllowed": False,
            "nationalProviderScrape": False,
            "maxTargets": MAX_TARGETS,
            "boundingBoxDegrees": BBOX_DEGREES,
        },
        "punTargetOperator": pun.get("targetOperator"),
        "targets": results,
    }
    out = Path("artifacts/go_electric_nextcharge_exact_match_probe.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    summary = []
    for r in results:
        nc = r.get("nextcharge") or {}
        summary.append({
            "powerClass": r["pun"].get("powerClass"),
            "punStationId": r["pun"].get("stationId"),
            "punName": r["pun"].get("name"),
            "punEvses": [x.get("evseId") for x in r["pun"].get("evses", [])],
            "matched": r.get("matched"),
            "nextchargeStationId": nc.get("idStation"),
            "distanceM": nc.get("distanceM"),
            "detailStatus": nc.get("detailHttpStatus"),
            "tariffEMPCount": len(nc.get("tariffEMP") or []),
            "priceRateStandardCount": len(nc.get("priceRateStandard") or []),
            "idEVSECount": len(nc.get("idEVSE") or []),
            "idConnectorCount": len(nc.get("idConnector") or []),
            "providerFields": nc.get("providerFields"),
        })
    print(json.dumps(summary, ensure_ascii=False, indent=2))

    if not any(r.get("matched") for r in results):
        raise SystemExit("no exact-target NextCharge station detail could be read")


if __name__ == "__main__":
    main()
